lucky = [4, 8, 15, 34, 16, 23, 42]
friends = ["Edwin", "Eldho", "Acquin", "Hussu", "Jaimy", "Rohit", "Gayu"]
print(friends)
friends.append("Jacob")
print(friends)
friends.insert(1,"Ed")
print(friends)
friends.remove("Jacob")
print(friends)
print(friends.count("Eldho"))
friends.sort()
print(friends)
friends.pop()
print(friends.index("Hussu"))
friends.clear()
print(friends)
print(friends)
friends.extend(lucky)
print(friends)
lucky.sort()
print(lucky)
lucky.reverse()
friends2 = friends.count()